name = "Etch Notation"
license = "MIT"
licenselink = "https://github.com/akherlan/etch-notation/blob/master/LICENSE"
description = "Lightweight Hugo theme with a focus on content (as notebook)"
homepage = "https://github.com/akherlan/etch-notation"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode", "notation"]
min_version = "0.41"

[author]
  name = "Lukas Joswiak"
  homepage = "https://lukasjoswiak.com"
